//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPS.ImportacaoDados.SitCamaraWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.camara.gov.br/SitCamaraWS/Deputados", ConfigurationName="SitCamaraWS.DeputadosSoap")]
    public interface DeputadosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDeputados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ObterDeputados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDeputados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDeputadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosCD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ObterPartidosCD();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosCD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosCDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosBlocoCD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ObterPartidosBlocoCD(string idBloco, string numLegislatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosBlocoCD", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosBlocoCDAsync(string idBloco, string numLegislatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDetalhesDeputado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ObterDetalhesDeputado(string ideCadastro, string numLegislatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDetalhesDeputado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDetalhesDeputadoAsync(string ideCadastro, string numLegislatura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterLideresBancadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ObterLideresBancadas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterLideresBancadas", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterLideresBancadasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterIdCadastroOrcamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ObterIdCadastroOrcamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.camara.gov.br/SitCamaraWS/Deputados/ObterIdCadastroOrcamento", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> ObterIdCadastroOrcamentoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeputadosSoapChannel : OPS.ImportacaoDados.SitCamaraWS.DeputadosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeputadosSoapClient : System.ServiceModel.ClientBase<OPS.ImportacaoDados.SitCamaraWS.DeputadosSoap>, OPS.ImportacaoDados.SitCamaraWS.DeputadosSoap {
        
        public DeputadosSoapClient() {
        }
        
        public DeputadosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeputadosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeputadosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeputadosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode ObterDeputados() {
            return base.Channel.ObterDeputados();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDeputadosAsync() {
            return base.Channel.ObterDeputadosAsync();
        }
        
        public System.Xml.XmlNode ObterPartidosCD() {
            return base.Channel.ObterPartidosCD();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosCDAsync() {
            return base.Channel.ObterPartidosCDAsync();
        }
        
        public System.Xml.XmlNode ObterPartidosBlocoCD(string idBloco, string numLegislatura) {
            return base.Channel.ObterPartidosBlocoCD(idBloco, numLegislatura);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterPartidosBlocoCDAsync(string idBloco, string numLegislatura) {
            return base.Channel.ObterPartidosBlocoCDAsync(idBloco, numLegislatura);
        }
        
        public System.Xml.XmlNode ObterDetalhesDeputado(string ideCadastro, string numLegislatura) {
            return base.Channel.ObterDetalhesDeputado(ideCadastro, numLegislatura);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterDetalhesDeputadoAsync(string ideCadastro, string numLegislatura) {
            return base.Channel.ObterDetalhesDeputadoAsync(ideCadastro, numLegislatura);
        }
        
        public System.Xml.XmlNode ObterLideresBancadas() {
            return base.Channel.ObterLideresBancadas();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterLideresBancadasAsync() {
            return base.Channel.ObterLideresBancadasAsync();
        }
        
        public System.Xml.XmlNode ObterIdCadastroOrcamento() {
            return base.Channel.ObterIdCadastroOrcamento();
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> ObterIdCadastroOrcamentoAsync() {
            return base.Channel.ObterIdCadastroOrcamentoAsync();
        }
    }
}
