-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS assembleias.cl_deputado
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    matricula integer,
    gabinete integer,
    id_partido smallint NOT NULL DEFAULT 0,
    id_estado smallint NOT NULL,
    cpf character varying(11) COLLATE pg_catalog."default",
    cpf_parcial character varying(6) COLLATE pg_catalog."default",
    nome_parlamentar character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nome_civil character varying(255) COLLATE pg_catalog."default",
    nome_importacao character varying(255) COLLATE pg_catalog."default",
    nascimento date,
    sexo character(2) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    naturalidade character varying(100) COLLATE pg_catalog."default",
    escolaridade character varying(100) COLLATE pg_catalog."default",
    profissao character varying(150) COLLATE pg_catalog."default",
    telefone character varying(100) COLLATE pg_catalog."default",
    site character varying(500) COLLATE pg_catalog."default",
    perfil character varying(100) COLLATE pg_catalog."default",
    foto character varying(200) COLLATE pg_catalog."default",
    valor_total_ceap numeric(12, 2) NOT NULL DEFAULT 0,
    valor_total_remuneracao numeric(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT cl_deputado_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE assembleias.cl_deputado
    IS 'Câmara Legislativa - Deputados Estaduais';

CREATE TABLE IF NOT EXISTS assembleias.cl_deputado_campeao_gasto
(
    id_cl_deputado integer NOT NULL,
    nome_parlamentar character varying(100) COLLATE pg_catalog."default",
    valor_total numeric(10, 2),
    sigla_partido character varying(20) COLLATE pg_catalog."default",
    sigla_estado character varying(2) COLLATE pg_catalog."default",
    CONSTRAINT cl_deputado_campeao_gasto_pkey PRIMARY KEY (id_cl_deputado)
);

CREATE TABLE IF NOT EXISTS assembleias.cl_despesa
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_cl_deputado integer NOT NULL,
    id_cl_despesa_tipo smallint,
    id_cl_despesa_especificacao smallint,
    id_fornecedor integer,
    data_emissao date,
    ano_mes integer,
    numero_documento character varying(50) COLLATE pg_catalog."default",
    valor_liquido numeric(10, 2) NOT NULL,
    favorecido character varying(200) COLLATE pg_catalog."default",
    observacao character varying(8000) COLLATE pg_catalog."default",
    hash bytea,
    CONSTRAINT cl_despesa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS assembleias.cl_despesa_especificacao
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    id_cl_despesa_tipo smallint,
    descricao character varying(400) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cl_despesa_especificacao_pkey PRIMARY KEY (id),
    CONSTRAINT cl_despesa_especificacao_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS assembleias.cl_despesa_resumo_mensal
(
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 2),
    CONSTRAINT cl_despesa_resumo_mensal_pkey PRIMARY KEY (ano, mes)
);

CREATE TABLE IF NOT EXISTS assembleias.cl_despesa_tipo
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cl_despesa_tipo_pkey PRIMARY KEY (id),
    CONSTRAINT cl_despesa_tipo_descricao_key UNIQUE (descricao)
);

ALTER TABLE IF EXISTS assembleias.cl_despesa
    ADD CONSTRAINT fk_cl_despesa_deputado FOREIGN KEY (id_cl_deputado)
    REFERENCES assembleias.cl_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS assembleias.cl_despesa
    ADD CONSTRAINT fk_cl_despesa_especificacao FOREIGN KEY (id_cl_despesa_especificacao)
    REFERENCES assembleias.cl_despesa_especificacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS assembleias.cl_despesa
    ADD CONSTRAINT fk_cl_despesa_tipo FOREIGN KEY (id_cl_despesa_tipo)
    REFERENCES assembleias.cl_despesa_tipo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS assembleias.cl_despesa_especificacao
    ADD CONSTRAINT fk_cl_despesa_especificacao_tipo FOREIGN KEY (id_cl_despesa_tipo)
    REFERENCES assembleias.cl_despesa_tipo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;