-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS camara.cf_deputado
(
    id integer NOT NULL,
    id_deputado integer,
    id_partido smallint NOT NULL,
    id_estado smallint,
    id_cf_gabinete smallint,
    cpf character varying(15) COLLATE pg_catalog."default",
    nome_parlamentar character varying(100) COLLATE pg_catalog."default",
    nome_civil character varying(100) COLLATE pg_catalog."default",
    nome_importacao_presenca character varying(100) COLLATE pg_catalog."default",
    sexo character varying(2) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    nascimento date,
    falecimento date,
    id_estado_nascimento smallint,
    municipio character varying(500) COLLATE pg_catalog."default",
    website character varying(255) COLLATE pg_catalog."default",
    profissao character varying(255) COLLATE pg_catalog."default",
    escolaridade character varying(100) COLLATE pg_catalog."default",
    condicao character varying(50) COLLATE pg_catalog."default",
    situacao character varying(20) COLLATE pg_catalog."default",
    passaporte_diplomatico boolean,
    processado boolean NOT NULL,
    valor_total_ceap numeric(16, 2) NOT NULL,
    secretarios_ativos smallint,
    valor_mensal_secretarios numeric(16, 2) NOT NULL,
    valor_total_remuneracao numeric(16, 2) NOT NULL,
    valor_total_salario numeric(16, 2) NOT NULL,
    valor_total_auxilio_moradia numeric(16, 2) NOT NULL,
    CONSTRAINT cf_deputado_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN camara.cf_deputado.id
    IS 'ideDeputado';

COMMENT ON COLUMN camara.cf_deputado.id_deputado
    IS 'nuDeputadoId';

COMMENT ON COLUMN camara.cf_deputado.id_cf_gabinete
    IS 'Usado para importação dos secretarios parlamentares';

COMMENT ON COLUMN camara.cf_deputado.valor_total_ceap
    IS 'Valor acumulado gasto com a cota parlamentar em todas as legislaturas';

COMMENT ON COLUMN camara.cf_deputado.secretarios_ativos
    IS 'Quantidade de secretarios';

COMMENT ON COLUMN camara.cf_deputado.valor_total_remuneracao
    IS 'Renomear para valor_total_gabinete';

COMMENT ON COLUMN camara.cf_deputado.valor_total_salario
    IS 'Renomear para valor_total_remuneracao';

CREATE TABLE IF NOT EXISTS camara.cf_deputado_auxilio_moradia
(
    id_cf_deputado integer NOT NULL,
    ano smallint,
    mes smallint,
    valor numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS camara.cf_deputado_campeao_gasto
(
    id_cf_deputado integer NOT NULL,
    nome_parlamentar character varying(100) COLLATE pg_catalog."default",
    valor_total numeric(10, 2),
    sigla_partido character varying(20) COLLATE pg_catalog."default",
    sigla_estado character varying(2) COLLATE pg_catalog."default",
    CONSTRAINT cf_deputado_campeao_gasto_pkey PRIMARY KEY (id_cf_deputado)
);

CREATE TABLE IF NOT EXISTS camara.cf_deputado_cota_parlamentar
(
    id_cf_deputado integer NOT NULL,
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 2) NOT NULL,
    percentual numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS camara.cf_deputado_imovel_funcional
(
    id_cf_deputado integer NOT NULL,
    uso_de date NOT NULL,
    uso_ate date,
    total_dias smallint
);

CREATE TABLE IF NOT EXISTS camara.cf_deputado_missao_oficial
(
    id_cf_deputado integer NOT NULL,
    periodo character varying(50) COLLATE pg_catalog."default" NOT NULL,
    assunto character varying(4000) COLLATE pg_catalog."default" NOT NULL,
    destino character varying(255) COLLATE pg_catalog."default",
    passagens numeric(10, 2),
    diarias numeric(10, 2),
    relatorio character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS camara.cf_deputado_remuneracao
(
    id_cf_deputado integer NOT NULL,
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS camara.cf_deputado_verba_gabinete
(
    id_cf_deputado integer NOT NULL,
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 2) NOT NULL,
    percentual numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS camara.cf_despesa
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ano integer NOT NULL,
    mes smallint NOT NULL,
    id_cf_legislatura smallint NOT NULL,
    id_cf_deputado integer NOT NULL,
    id_cf_mandato integer,
    id_cf_despesa_tipo smallint NOT NULL,
    id_cf_especificacao smallint,
    id_fornecedor integer NOT NULL,
    id_documento integer,
    id_passageiro integer,
    id_trecho_viagem integer,
    data_emissao date,
    valor_documento numeric(10, 2),
    valor_glosa numeric(10, 2) NOT NULL,
    valor_liquido numeric(10, 2) NOT NULL,
    valor_restituicao numeric(10, 2),
    tipo_documento smallint NOT NULL,
    tipo_link smallint NOT NULL,
    numero_documento character varying(100) COLLATE pg_catalog."default",
    hash bytea,
    ano_mes integer,
    CONSTRAINT cf_despesa_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN camara.cf_despesa.tipo_documento
    IS '0: Nota Fiscal; 1: Recibo; 2: Despesa no Exterior';

COMMENT ON COLUMN camara.cf_despesa.tipo_link
    IS '0: Sem Arquivo; 1: Recibo; 2: Nota Fiscal Eletronica';

CREATE TABLE IF NOT EXISTS camara.cf_despesa_resumo_mensal
(
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 2),
    CONSTRAINT cf_despesa_resumo_mensal_pkey PRIMARY KEY (ano, mes)
);

CREATE TABLE IF NOT EXISTS camara.cf_despesa_tipo
(
    id smallint NOT NULL,
    descricao character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT cf_despesa_tipo_pkey PRIMARY KEY (id),
    CONSTRAINT cf_despesa_tipo_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS camara.cf_especificacao_tipo
(
    id_cf_despesa_tipo smallint NOT NULL,
    id_cf_especificacao smallint NOT NULL,
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cf_especificacao_tipo_pkey PRIMARY KEY (id_cf_especificacao),
    CONSTRAINT cf_especificacao_tipo_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    chave character varying(45) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    processado boolean NOT NULL,
    controle character(10) COLLATE pg_catalog."default",
    CONSTRAINT cf_funcionario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_area_atuacao
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT cf_funcionario_area_atuacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_cargo
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT cf_funcionario_cargo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_contratacao
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cf_deputado integer,
    id_cf_funcionario integer NOT NULL,
    id_cf_funcionario_grupo_funcional smallint,
    id_cf_funcionario_cargo smallint,
    id_cf_funcionario_nivel smallint,
    id_cf_funcionario_funcao_comissionada smallint,
    id_cf_funcionario_area_atuacao smallint,
    id_cf_funcionario_local_trabalho smallint,
    id_cf_funcionario_situacao smallint,
    periodo_de date,
    periodo_ate date,
    CONSTRAINT cf_funcionario_contratacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_funcao_comissionada
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT cf_funcionario_funcao_comissionada_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_grupo_funcional
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cf_funcionario_grupo_funcional_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_local_trabalho
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT cf_funcionario_local_trabalho_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_nivel
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT cf_funcionario_nivel_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_remuneracao
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cf_funcionario integer NOT NULL,
    id_cf_funcionario_contratacao integer,
    id_cf_deputado integer,
    referencia date NOT NULL,
    id_cf_funcionario_tipo_folha smallint,
    remuneracao_fixa numeric(10, 2),
    vantagens_natureza_pessoal numeric(10, 2),
    funcao_ou_cargo_em_comissao numeric(10, 2),
    gratificacao_natalina numeric(10, 2),
    ferias numeric(10, 2),
    outras_remuneracoes numeric(10, 2),
    abono_permanencia numeric(10, 2),
    valor_bruto numeric(10, 2),
    redutor_constitucional numeric(10, 2),
    contribuicao_previdenciaria numeric(10, 2),
    imposto_renda numeric(10, 2),
    valor_liquido numeric(10, 2),
    valor_diarias numeric(10, 2),
    valor_auxilios numeric(10, 2),
    valor_vantagens numeric(10, 2),
    valor_outros numeric(10, 2),
    valor_total numeric(10, 2),
    nivel character varying(5) COLLATE pg_catalog."default",
    contratacao date,
    CONSTRAINT cf_funcionario_remuneracao_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN camara.cf_funcionario_remuneracao.valor_total
    IS 'valor_bruto + valor_outros';

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_situacao
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT cf_funcionario_situacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_funcionario_tipo_folha
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cf_funcionario_tipo_folha_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_gabinete
(
    id smallint NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default",
    predio character varying(50) COLLATE pg_catalog."default",
    andar smallint,
    sala character varying(50) COLLATE pg_catalog."default",
    telefone character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT cf_gabinete_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_legislatura
(
    id smallint NOT NULL,
    ano smallint,
    inicio integer,
    final integer,
    CONSTRAINT cf_legislatura_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_mandato
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cf_deputado integer NOT NULL,
    id_legislatura smallint,
    id_carteira_parlamantar smallint,
    id_estado smallint,
    id_partido smallint,
    condicao character varying(10) COLLATE pg_catalog."default",
    valor_total_ceap numeric(10, 2),
    CONSTRAINT cf_mandato_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_secretario
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cf_deputado integer NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    periodo character varying(100) COLLATE pg_catalog."default",
    cargo character varying(45) COLLATE pg_catalog."default",
    valor_bruto numeric(10, 2),
    valor_liquido numeric(10, 2),
    valor_outros numeric(10, 2),
    link character varying(255) COLLATE pg_catalog."default",
    referencia character varying(255) COLLATE pg_catalog."default",
    em_exercicio boolean,
    CONSTRAINT cf_secretario_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_secretario_historico
(
    id_cf_deputado integer NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    cargo character varying(45) COLLATE pg_catalog."default",
    periodo character varying(255) COLLATE pg_catalog."default",
    valor_bruto numeric(10, 2),
    valor_liquido numeric(10, 2),
    valor_outros numeric(10, 2),
    link character varying(255) COLLATE pg_catalog."default",
    referencia character varying(255) COLLATE pg_catalog."default",
    ano_mes integer
);

CREATE TABLE IF NOT EXISTS camara.cf_sessao
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_legislatura smallint NOT NULL,
    data date NOT NULL,
    inicio timestamp(6) without time zone NOT NULL,
    tipo smallint NOT NULL,
    numero character varying(45) COLLATE pg_catalog."default",
    presencas smallint NOT NULL,
    ausencias smallint NOT NULL,
    ausencias_justificadas smallint NOT NULL,
    checksum character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT cf_sessao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS camara.cf_sessao_presenca
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_cf_sessao integer NOT NULL,
    id_cf_deputado integer NOT NULL,
    presente boolean NOT NULL,
    justificativa character varying(100) COLLATE pg_catalog."default",
    presenca_externa boolean NOT NULL,
    CONSTRAINT cf_sessao_presenca_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS camara.cf_deputado
    ADD CONSTRAINT fk_cf_deputado_gabinete FOREIGN KEY (id_cf_gabinete)
    REFERENCES camara.cf_gabinete (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_cf_gabinete
    ON camara.cf_deputado(id_cf_gabinete);


ALTER TABLE IF EXISTS camara.cf_deputado_auxilio_moradia
    ADD CONSTRAINT fk_cf_deputado_auxilio_moradia_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_deputado_campeao_gasto
    ADD CONSTRAINT cf_deputado_campeao_gasto_id_cf_deputado_fkey FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS cf_deputado_campeao_gasto_pkey
    ON camara.cf_deputado_campeao_gasto(id_cf_deputado);


ALTER TABLE IF EXISTS camara.cf_deputado_cota_parlamentar
    ADD CONSTRAINT fk_cf_deputado_cota_parlamentar_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_cl_deputado
    ON camara.cf_deputado_cota_parlamentar(id_cf_deputado);


ALTER TABLE IF EXISTS camara.cf_deputado_imovel_funcional
    ADD CONSTRAINT fk_cf_deputado_imovel_funcional_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_deputado_missao_oficial
    ADD CONSTRAINT fk_cf_deputado_missao_oficial_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_deputado_remuneracao
    ADD CONSTRAINT fk_cf_deputado_remuneracao_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_deputado_verba_gabinete
    ADD CONSTRAINT fk_cf_deputado_verba_gabinete_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_despesa
    ADD CONSTRAINT fk_cf_despesa_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_id_cf_deputado
    ON camara.cf_despesa(id_cf_deputado);


ALTER TABLE IF EXISTS camara.cf_despesa
    ADD CONSTRAINT fk_cf_despesa_especificacao FOREIGN KEY (id_cf_especificacao)
    REFERENCES camara.cf_especificacao_tipo (id_cf_especificacao) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_cf_especificacao
    ON camara.cf_despesa(id_cf_especificacao);


ALTER TABLE IF EXISTS camara.cf_despesa
    ADD CONSTRAINT fk_cf_despesa_legislatura FOREIGN KEY (id_cf_legislatura)
    REFERENCES camara.cf_legislatura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_legislatura
    ON camara.cf_despesa(id_cf_legislatura);


ALTER TABLE IF EXISTS camara.cf_despesa
    ADD CONSTRAINT fk_cf_despesa_mandato FOREIGN KEY (id_cf_mandato)
    REFERENCES camara.cf_mandato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_cf_mandato
    ON camara.cf_despesa(id_cf_mandato);


ALTER TABLE IF EXISTS camara.cf_despesa
    ADD CONSTRAINT fk_cf_despesa_tipo FOREIGN KEY (id_cf_despesa_tipo)
    REFERENCES camara.cf_despesa_tipo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_cf_despesa_tipo
    ON camara.cf_despesa(id_cf_despesa_tipo);


ALTER TABLE IF EXISTS camara.cf_especificacao_tipo
    ADD CONSTRAINT fk_cf_especificacao_tipo_despesa_tipo FOREIGN KEY (id_cf_despesa_tipo)
    REFERENCES camara.cf_despesa_tipo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_area_atuacao FOREIGN KEY (id_cf_funcionario_area_atuacao)
    REFERENCES camara.cf_funcionario_area_atuacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_funcionario_area_atuacao"
    ON camara.cf_funcionario_contratacao(id_cf_funcionario_area_atuacao);


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_cargo FOREIGN KEY (id_cf_funcionario_cargo)
    REFERENCES camara.cf_funcionario_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_funcionario_cargo"
    ON camara.cf_funcionario_contratacao(id_cf_funcionario_cargo);


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_deputado"
    ON camara.cf_funcionario_contratacao(id_cf_deputado);


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_funcao_comissionada FOREIGN KEY (id_cf_funcionario_funcao_comissionada)
    REFERENCES camara.cf_funcionario_funcao_comissionada (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_funcionario_funcao_comissionad"
    ON camara.cf_funcionario_contratacao(id_cf_funcionario_funcao_comissionada);


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_funcionario FOREIGN KEY (id_cf_funcionario)
    REFERENCES camara.cf_funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_grupo_funcional FOREIGN KEY (id_cf_funcionario_grupo_funcional)
    REFERENCES camara.cf_funcionario_grupo_funcional (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_funcionario_grupo_funcional"
    ON camara.cf_funcionario_contratacao(id_cf_funcionario_grupo_funcional);


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_local_trabalho FOREIGN KEY (id_cf_funcionario_local_trabalho)
    REFERENCES camara.cf_funcionario_local_trabalho (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_funcionario_local_trabalho"
    ON camara.cf_funcionario_contratacao(id_cf_funcionario_local_trabalho);


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_nivel FOREIGN KEY (id_cf_funcionario_nivel)
    REFERENCES camara.cf_funcionario_nivel (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_funcionario_nivel"
    ON camara.cf_funcionario_contratacao(id_cf_funcionario_nivel);


ALTER TABLE IF EXISTS camara.cf_funcionario_contratacao
    ADD CONSTRAINT fk_cf_funcionario_contratacao_situacao FOREIGN KEY (id_cf_funcionario_situacao)
    REFERENCES camara.cf_funcionario_situacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_contratacao_cf_funcionario_situacao"
    ON camara.cf_funcionario_contratacao(id_cf_funcionario_situacao);


ALTER TABLE IF EXISTS camara.cf_funcionario_remuneracao
    ADD CONSTRAINT cf_funcionario_remuneracao_id_cf_funcionario_tipo_folha_fkey FOREIGN KEY (id_cf_funcionario_tipo_folha)
    REFERENCES camara.cf_funcionario_tipo_folha (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS camara.cf_funcionario_remuneracao
    ADD CONSTRAINT fk_cf_funcionario_remuneracao_contratacao FOREIGN KEY (id_cf_funcionario_contratacao)
    REFERENCES camara.cf_funcionario_contratacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_remuneracao_cf_funcionario_contratacao"
    ON camara.cf_funcionario_remuneracao(id_cf_funcionario_contratacao);


ALTER TABLE IF EXISTS camara.cf_funcionario_remuneracao
    ADD CONSTRAINT fk_cf_funcionario_remuneracao_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK_cf_funcionario_remuneracao_cf_deputado"
    ON camara.cf_funcionario_remuneracao(id_cf_deputado);


ALTER TABLE IF EXISTS camara.cf_funcionario_remuneracao
    ADD CONSTRAINT fk_cf_funcionario_remuneracao_funcionario FOREIGN KEY (id_cf_funcionario)
    REFERENCES camara.cf_funcionario (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_mandato
    ADD CONSTRAINT fk_cf_mandato_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_mandato
    ADD CONSTRAINT fk_cf_mandato_legislatura FOREIGN KEY (id_legislatura)
    REFERENCES camara.cf_legislatura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_secretario
    ADD CONSTRAINT fk_cf_secretario_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_secretario_historico
    ADD CONSTRAINT fk_cf_secretario_historico_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_sessao
    ADD CONSTRAINT fk_cf_sessao_legislatura FOREIGN KEY (id_legislatura)
    REFERENCES camara.cf_legislatura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_sessao_presenca
    ADD CONSTRAINT fk_cf_sessao_presenca_deputado FOREIGN KEY (id_cf_deputado)
    REFERENCES camara.cf_deputado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS camara.cf_sessao_presenca
    ADD CONSTRAINT fk_cf_sessao_presenca_sessao FOREIGN KEY (id_cf_sessao)
    REFERENCES camara.cf_sessao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_cf_sessao
    ON camara.cf_sessao_presenca(id_cf_sessao);

END;