-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS public.estado
(
    id smallint NOT NULL,
    sigla character(2) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    regiao character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estado_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.estado
    IS 'https://ibge.gov.br/explica/codigos-dos-municipios.php';

COMMENT ON COLUMN public.estado.id
    IS 'Código no IBGE';

CREATE TABLE IF NOT EXISTS public.estado_civil
(
    id smallint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT estado_civil_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.estado_civil.id
    IS 'Código no TSE';

CREATE TABLE IF NOT EXISTS public.etnia
(
    id smallint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT etnia_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.etnia.id
    IS 'Código no TSE';

CREATE TABLE IF NOT EXISTS public.genero
(
    id smallint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT genero_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.genero.id
    IS 'Código no TSE';

CREATE TABLE IF NOT EXISTS public.grau_instrucao
(
    id integer NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT grau_instrucao_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.grau_instrucao.id
    IS 'Código no TSE';

CREATE TABLE IF NOT EXISTS public.importacao
(
    id smallint NOT NULL,
    chave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    info character varying(255) COLLATE pg_catalog."default" NOT NULL,
    parlamentar_inicio timestamp without time zone,
    parlamentar_fim timestamp without time zone,
    despesas_inicio timestamp without time zone,
    despesas_fim timestamp without time zone,
    primeira_despesa date,
    ultima_despesa date,
    id_estado smallint
);

CREATE TABLE IF NOT EXISTS public.indice_inflacao
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 4) NOT NULL,
    indice numeric(38, 10) NOT NULL,
    CONSTRAINT indice_inflacao_pkey PRIMARY KEY (id),
    CONSTRAINT indice_inflacao_ano_mes_key UNIQUE (ano, mes)
);

CREATE TABLE IF NOT EXISTS public.municipio
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_estado smallint NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT municipio_pkey PRIMARY KEY (id),
    CONSTRAINT municipio_id_estado_nome_key UNIQUE (id_estado, nome)
);

COMMENT ON TABLE public.municipio
    IS 'Imported from: https://github.com/franciskaster/api-cidades-brasil';

CREATE TABLE IF NOT EXISTS public.pais
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    sigla text COLLATE pg_catalog."default",
    nome text COLLATE pg_catalog."default",
    CONSTRAINT pk_pais PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partido
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    legenda smallint,
    sigla character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    imagem character varying(100) COLLATE pg_catalog."default",
    ativo boolean NOT NULL DEFAULT true,
    sede character(2) COLLATE pg_catalog."default",
    fundacao date,
    registro_solicitacao date,
    registro_provisorio date,
    registro_definitivo date,
    extincao date,
    motivo character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT partido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pessoa
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cpf character varying(15) COLLATE pg_catalog."default",
    nome character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT pessoa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.profissao
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default",
    codigo_tse integer,
    CONSTRAINT profissao_pkey PRIMARY KEY (id),
    CONSTRAINT profissao_descricao_key UNIQUE (descricao)
);

COMMENT ON COLUMN public.profissao.codigo_tse
    IS 'Chave TSE';

CREATE TABLE IF NOT EXISTS public.trecho_viagem
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT trecho_viagem_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.importacao
    ADD CONSTRAINT importacao_id_estado_fkey FOREIGN KEY (id_estado)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.municipio
    ADD CONSTRAINT municipio_id_estado_fkey FOREIGN KEY (id_estado)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;