-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS public.estado
(
    id smallint NOT NULL,
    sigla character(2) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(30) COLLATE pg_catalog."default" NOT NULL,
    regiao character varying(30) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT estado_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.estado
    IS 'https://ibge.gov.br/explica/codigos-dos-municipios.php';

COMMENT ON COLUMN public.estado.id
    IS 'Código no IBGE';

CREATE TABLE IF NOT EXISTS public.importacao
(
    id smallint NOT NULL,
    chave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    info character varying(255) COLLATE pg_catalog."default" NOT NULL,
    parlamentar_inicio timestamp without time zone,
    parlamentar_fim timestamp without time zone,
    despesas_inicio timestamp without time zone,
    despesas_fim timestamp without time zone,
    primeira_despesa date,
    ultima_despesa date,
    id_estado smallint
);

CREATE TABLE IF NOT EXISTS public.partido
(
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    legenda smallint,
    sigla character varying(20) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default",
    imagem character varying(100) COLLATE pg_catalog."default",
    ativo boolean NOT NULL DEFAULT true,
    sede character(2) COLLATE pg_catalog."default",
    fundacao date,
    registro_solicitacao date,
    registro_provisorio date,
    registro_definitivo date,
    extincao date,
    motivo character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT partido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.partido_historico
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    legenda smallint,
    sigla character varying(20) COLLATE pg_catalog."default",
    nome character varying(100) COLLATE pg_catalog."default",
    sede character(2) COLLATE pg_catalog."default",
    fundacao date,
    registro_solicitacao date,
    registro_provisorio date,
    registro_definitivo date,
    extincao date,
    motivo character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT partido_historico_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.partido_historico
    IS 'https://www.partidosdobrasil.com/';

COMMENT ON COLUMN public.partido_historico.fundacao
    IS 'Fundação';

COMMENT ON COLUMN public.partido_historico.registro_solicitacao
    IS 'Solitação de habilitação ou registro';

COMMENT ON COLUMN public.partido_historico.registro_provisorio
    IS 'Registro provisório';

COMMENT ON COLUMN public.partido_historico.registro_definitivo
    IS 'Registro definitivo';

COMMENT ON COLUMN public.partido_historico.extincao
    IS 'Extinção';

CREATE TABLE IF NOT EXISTS public.pessoa
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cpf character varying(15) COLLATE pg_catalog."default",
    nome character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT pessoa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.pessoa_new
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    cpf character varying(15) COLLATE pg_catalog."default" NOT NULL,
    cpf_parcial character varying(6) COLLATE pg_catalog."default",
    nome character varying(100) COLLATE pg_catalog."default",
    data_nascimento date,
    id_nacionalidade smallint,
    id_estado_nascimento integer,
    municipio_nascimento character varying(100) COLLATE pg_catalog."default",
    id_genero smallint,
    id_etnia smallint,
    id_estado_civil smallint,
    id_grau_instrucao smallint,
    id_ocupacao integer,
    CONSTRAINT pessoa_new_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.profissao
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT profissao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.trecho_viagem
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    descricao character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT trecho_viagem_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.importacao
    ADD CONSTRAINT importacao_id_estado_fkey FOREIGN KEY (id_estado)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pessoa_new
    ADD CONSTRAINT fk_pessoa_new_estado_civil FOREIGN KEY (id_estado_civil)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pessoa_new
    ADD CONSTRAINT fk_pessoa_new_estado_nascimento FOREIGN KEY (id_estado_nascimento)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pessoa_new
    ADD CONSTRAINT fk_pessoa_new_etnia FOREIGN KEY (id_etnia)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pessoa_new
    ADD CONSTRAINT fk_pessoa_new_genero FOREIGN KEY (id_genero)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pessoa_new
    ADD CONSTRAINT fk_pessoa_new_grau_instrucao FOREIGN KEY (id_grau_instrucao)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pessoa_new
    ADD CONSTRAINT fk_pessoa_new_nacionalidade FOREIGN KEY (id_nacionalidade)
    REFERENCES public.estado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.pessoa_new
    ADD CONSTRAINT fk_pessoa_new_ocupacao FOREIGN KEY (id_ocupacao)
    REFERENCES public.profissao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;