-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS fornecedor.fornecedor
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cnpj_cpf character varying(15) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    categoria character(2) COLLATE pg_catalog."default",
    doador boolean NOT NULL DEFAULT false,
    controle smallint,
    mensagem character varying(8000) COLLATE pg_catalog."default",
    valor_total_ceap_camara numeric(16, 2),
    valor_total_ceap_senado numeric(16, 2),
    valor_total_ceap_assembleias numeric(16, 2),
    CONSTRAINT fornecedor_pkey PRIMARY KEY (id),
    CONSTRAINT fornecedor_cnpj_cpf_key UNIQUE (cnpj_cpf)
);

COMMENT ON COLUMN fornecedor.fornecedor.categoria
    IS 'Pessoa Fisica ou Pessoa Juridica';

CREATE TABLE IF NOT EXISTS fornecedor.fornecedor_atividade
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    codigo character varying(15) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fornecedor_atividade_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS fornecedor.fornecedor_atividade_secundaria
(
    id_fornecedor integer NOT NULL,
    id_fornecedor_atividade smallint NOT NULL,
    CONSTRAINT fornecedor_atividade_secundaria_pkey PRIMARY KEY (id_fornecedor, id_fornecedor_atividade)
);

CREATE TABLE IF NOT EXISTS fornecedor.fornecedor_faixa_etaria
(
    id smallint NOT NULL,
    nome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT fornecedor_faixa_etaria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS fornecedor.fornecedor_info
(
    id_fornecedor integer NOT NULL,
    cnpj character varying(14) COLLATE pg_catalog."default" NOT NULL,
    cnpj_radical character(14) COLLATE pg_catalog."default",
    tipo character(20) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    data_de_abertura date,
    nome_fantasia character varying(255) COLLATE pg_catalog."default",
    id_fornecedor_atividade_principal smallint,
    id_fornecedor_natureza_juridica smallint,
    logradouro_tipo character varying(20) COLLATE pg_catalog."default",
    logradouro character varying(100) COLLATE pg_catalog."default",
    numero character varying(100) COLLATE pg_catalog."default",
    complemento character varying(150) COLLATE pg_catalog."default",
    cep character varying(20) COLLATE pg_catalog."default",
    bairro character varying(100) COLLATE pg_catalog."default",
    municipio character varying(100) COLLATE pg_catalog."default",
    estado character varying(4) COLLATE pg_catalog."default",
    endereco_eletronico character varying(100) COLLATE pg_catalog."default",
    telefone1 character varying(100) COLLATE pg_catalog."default",
    telefone2 character varying(100) COLLATE pg_catalog."default",
    fax character varying(100) COLLATE pg_catalog."default",
    ente_federativo_responsavel character varying(100) COLLATE pg_catalog."default",
    situacao_cadastral character varying(100) COLLATE pg_catalog."default",
    data_da_situacao_cadastral date,
    motivo_situacao_cadastral character varying(100) COLLATE pg_catalog."default",
    situacao_especial character varying(100) COLLATE pg_catalog."default",
    data_situacao_especial date,
    capital_social numeric(20, 2),
    porte character varying(50) COLLATE pg_catalog."default",
    data_opcao_pelo_mei date,
    data_exclusao_do_mei date,
    data_opcao_pelo_simples date,
    data_exclusao_do_simples date,
    codigo_municipio character varying(50) COLLATE pg_catalog."default",
    codigo_municipio_ibge character varying(50) COLLATE pg_catalog."default",
    nome_cidade_no_exterior character varying(100) COLLATE pg_catalog."default",
    obtido_em date,
    ip_colaborador character varying(15) COLLATE pg_catalog."default",
    pais character varying(15) COLLATE pg_catalog."default",
    nome_pais character varying(100) COLLATE pg_catalog."default",
    opcao_pelo_mei boolean,
    opcao_pelo_simples boolean,
    CONSTRAINT fornecedor_info_pkey PRIMARY KEY (id_fornecedor),
    CONSTRAINT fornecedor_info_cnpj_key UNIQUE (cnpj)
);

CREATE TABLE IF NOT EXISTS fornecedor.fornecedor_natureza_juridica
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fornecedor_natureza_juridica_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS fornecedor.fornecedor_socio
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_fornecedor integer NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default",
    cnpj_cpf character varying(15) COLLATE pg_catalog."default",
    pais_origem character varying(255) COLLATE pg_catalog."default",
    data_entrada_sociedade date,
    id_fornecedor_faixa_etaria smallint,
    id_fornecedor_socio_qualificacao smallint,
    nome_representante character varying(255) COLLATE pg_catalog."default",
    cpf_representante character varying(15) COLLATE pg_catalog."default",
    id_fornecedor_socio_representante_qualificacao smallint,
    CONSTRAINT fornecedor_socio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS fornecedor.fornecedor_socio_qualificacao
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT fornecedor_socio_qualificacao_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS fornecedor.fornecedor_atividade_secundaria
    ADD CONSTRAINT fk_fornecedor_atividade_secundaria_atividade FOREIGN KEY (id_fornecedor_atividade)
    REFERENCES fornecedor.fornecedor_atividade (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS fornecedor.fornecedor_atividade_secundaria
    ADD CONSTRAINT fk_fornecedor_atividade_secundaria_fornecedor FOREIGN KEY (id_fornecedor)
    REFERENCES fornecedor.fornecedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS fornecedor.fornecedor_info
    ADD CONSTRAINT fk_fornecedor_info_atividade_principal FOREIGN KEY (id_fornecedor_atividade_principal)
    REFERENCES fornecedor.fornecedor_atividade (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_fornecedor_atividade_principal
    ON fornecedor.fornecedor_info(id_fornecedor_atividade_principal);


ALTER TABLE IF EXISTS fornecedor.fornecedor_info
    ADD CONSTRAINT fk_fornecedor_info_fornecedor FOREIGN KEY (id_fornecedor)
    REFERENCES fornecedor.fornecedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS fornecedor_info_pkey
    ON fornecedor.fornecedor_info(id_fornecedor);


ALTER TABLE IF EXISTS fornecedor.fornecedor_info
    ADD CONSTRAINT fk_fornecedor_info_natureza_juridica FOREIGN KEY (id_fornecedor_natureza_juridica)
    REFERENCES fornecedor.fornecedor_natureza_juridica (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_fornecedor_natureza_juridica
    ON fornecedor.fornecedor_info(id_fornecedor_natureza_juridica);


ALTER TABLE IF EXISTS fornecedor.fornecedor_socio
    ADD CONSTRAINT fk_fornecedor_socio_faixa_etaria FOREIGN KEY (id_fornecedor_faixa_etaria)
    REFERENCES fornecedor.fornecedor_faixa_etaria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS fornecedor.fornecedor_socio
    ADD CONSTRAINT fk_fornecedor_socio_fornecedor FOREIGN KEY (id_fornecedor)
    REFERENCES fornecedor.fornecedor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_fornecedor
    ON fornecedor.fornecedor_socio(id_fornecedor);


ALTER TABLE IF EXISTS fornecedor.fornecedor_socio
    ADD CONSTRAINT fk_fornecedor_socio_qualificacao FOREIGN KEY (id_fornecedor_socio_qualificacao)
    REFERENCES fornecedor.fornecedor_socio_qualificacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_fornecedor_socio_qualificacao
    ON fornecedor.fornecedor_socio(id_fornecedor_socio_qualificacao);


ALTER TABLE IF EXISTS fornecedor.fornecedor_socio
    ADD CONSTRAINT fk_fornecedor_socio_representante_qualificacao FOREIGN KEY (id_fornecedor_socio_representante_qualificacao)
    REFERENCES fornecedor.fornecedor_socio_qualificacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_fornecedor_socio_representante_qualificacao
    ON fornecedor.fornecedor_socio(id_fornecedor_socio_representante_qualificacao);

END;