-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS senado.sf_cargo
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_cargo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_categoria
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_categoria_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_despesa
(
    id bigint NOT NULL,
    id_sf_senador integer NOT NULL,
    id_sf_despesa_tipo smallint,
    id_fornecedor integer,
    ano_mes integer,
    ano smallint,
    mes smallint,
    documento character varying(50) COLLATE pg_catalog."default",
    data_emissao date,
    detalhamento text COLLATE pg_catalog."default",
    valor numeric(10, 2),
    hash bytea,
    CONSTRAINT sf_despesa_pkey PRIMARY KEY (id_sf_senador, id)
);

CREATE TABLE IF NOT EXISTS senado.sf_despesa_resumo_mensal
(
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 2),
    CONSTRAINT sf_despesa_resumo_mensal_pkey PRIMARY KEY (ano, mes)
);

CREATE TABLE IF NOT EXISTS senado.sf_despesa_tipo
(
    id smallint NOT NULL,
    descricao character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_despesa_tipo_pkey PRIMARY KEY (id),
    CONSTRAINT sf_despesa_tipo_descricao_key UNIQUE (descricao)
);

CREATE TABLE IF NOT EXISTS senado.sf_funcao
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character(5) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_funcao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_legislatura
(
    id smallint NOT NULL,
    inicio date NOT NULL,
    final date NOT NULL,
    CONSTRAINT sf_legislatura_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_lotacao
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    id_senador integer,
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_lotacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_mandato
(
    id smallint NOT NULL,
    id_sf_senador integer NOT NULL,
    id_estado smallint,
    id_partido smallint,
    participacao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    exerceu boolean NOT NULL,
    CONSTRAINT sf_mandato_pkey PRIMARY KEY (id, id_sf_senador)
);

CREATE TABLE IF NOT EXISTS senado.sf_mandato_exercicio
(
    id integer NOT NULL,
    id_sf_senador integer NOT NULL,
    id_sf_mandato smallint NOT NULL,
    id_sf_motivo_afastamento character(5) COLLATE pg_catalog."default",
    inicio date,
    final date,
    CONSTRAINT sf_mandato_exercicio_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_mandato_legislatura
(
    id_sf_mandato smallint NOT NULL,
    id_sf_legislatura smallint NOT NULL,
    id_sf_senador integer NOT NULL,
    CONSTRAINT sf_mandato_legislatura_pkey PRIMARY KEY (id_sf_mandato, id_sf_legislatura)
);

CREATE TABLE IF NOT EXISTS senado.sf_motivo_afastamento
(
    id character varying(5) COLLATE pg_catalog."default" NOT NULL,
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_motivo_afastamento_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_referencia_cargo
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_referencia_cargo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_remuneracao
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_vinculo smallint NOT NULL,
    id_categoria smallint NOT NULL,
    id_cargo smallint,
    id_referencia_cargo smallint,
    id_simbolo_funcao smallint,
    id_lotacao smallint NOT NULL,
    id_tipo_folha smallint NOT NULL,
    ano_mes integer,
    admissao smallint NOT NULL,
    remun_basica numeric(10, 2),
    vant_pessoais numeric(10, 2),
    func_comissionada numeric(10, 2),
    grat_natalina numeric(10, 2),
    horas_extras numeric(10, 2),
    outras_eventuais numeric(10, 2),
    abono_permanencia numeric(10, 2),
    reversao_teto_const numeric(10, 2),
    imposto_renda numeric(10, 2),
    previdencia numeric(10, 2),
    faltas numeric(10, 2),
    rem_liquida numeric(10, 2),
    diarias numeric(10, 2),
    auxilios numeric(10, 2),
    vant_indenizatorias numeric(10, 2),
    custo_total numeric(10, 2),
    CONSTRAINT sf_remuneracao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_secretario
(
    id integer,
    id_senador integer,
    nome character varying(255) COLLATE pg_catalog."default",
    id_funcao smallint,
    id_cargo smallint,
    id_vinculo smallint,
    id_categoria smallint,
    id_referencia_cargo smallint,
    id_especialidade smallint,
    id_lotacao smallint,
    admissao smallint,
    id_sf_situacao smallint
);

CREATE TABLE IF NOT EXISTS senado.sf_senador
(
    id integer NOT NULL,
    codigo integer,
    nome character varying(255) COLLATE pg_catalog."default",
    nome_completo character varying(255) COLLATE pg_catalog."default",
    sexo character(1) COLLATE pg_catalog."default",
    nascimento date,
    naturalidade character varying(50) COLLATE pg_catalog."default",
    id_estado_naturalidade smallint,
    profissao character varying(100) COLLATE pg_catalog."default",
    id_partido smallint NOT NULL,
    id_estado smallint,
    email character varying(100) COLLATE pg_catalog."default",
    site character varying(100) COLLATE pg_catalog."default",
    ativo character(1) COLLATE pg_catalog."default",
    nome_importacao character varying(255) COLLATE pg_catalog."default",
    valor_total_ceaps numeric(16, 2) NOT NULL,
    valor_total_remuneracao numeric(16, 2) NOT NULL,
    hash bytea,
    exerceu_mandato boolean NOT NULL DEFAULT false,
    CONSTRAINT sf_senador_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_senador_campeao_gasto
(
    id_sf_senador integer NOT NULL,
    nome_parlamentar character varying(100) COLLATE pg_catalog."default",
    valor_total numeric(10, 2),
    sigla_partido character varying(20) COLLATE pg_catalog."default",
    sigla_estado character varying(2) COLLATE pg_catalog."default",
    CONSTRAINT sf_senador_campeao_gasto_pkey PRIMARY KEY (id_sf_senador)
);

CREATE TABLE IF NOT EXISTS senado.sf_senador_historico_academico
(
    id_sf_senador integer NOT NULL,
    nome_curso character varying(255) COLLATE pg_catalog."default" NOT NULL,
    grau_instrucao character varying(50) COLLATE pg_catalog."default",
    estabelecimento character varying(255) COLLATE pg_catalog."default",
    local character varying(255) COLLATE pg_catalog."default",
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT sf_senador_historico_academico_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_senador_partido
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_sf_senador integer NOT NULL,
    id_partido smallint NOT NULL,
    filiacao date,
    desfiliacao date,
    CONSTRAINT sf_senador_partido_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_senador_profissao
(
    id_sf_senador integer NOT NULL,
    id_profissao smallint NOT NULL,
    CONSTRAINT sf_senador_profissao_pkey PRIMARY KEY (id_sf_senador, id_profissao)
);

CREATE TABLE IF NOT EXISTS senado.sf_senador_verba_gabinete
(
    id_sf_senador integer NOT NULL,
    ano smallint NOT NULL,
    mes smallint NOT NULL,
    valor numeric(10, 2) NOT NULL,
    percentual numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS senado.sf_situacao
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_situacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_tipo_folha
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_tipo_folha_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS senado.sf_vinculo
(
    id smallint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    descricao character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT sf_vinculo_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS senado.sf_despesa
    ADD CONSTRAINT fk_sf_despesa_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_despesa
    ADD CONSTRAINT fk_sf_despesa_tipo FOREIGN KEY (id_sf_despesa_tipo)
    REFERENCES senado.sf_despesa_tipo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_sf_despesa_tipo
    ON senado.sf_despesa(id_sf_despesa_tipo);


ALTER TABLE IF EXISTS senado.sf_lotacao
    ADD CONSTRAINT fk_sf_lotacao_senador FOREIGN KEY (id_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_senador
    ON senado.sf_lotacao(id_senador);


ALTER TABLE IF EXISTS senado.sf_mandato
    ADD CONSTRAINT sf_mandato_id_sf_senador_fkey FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS senado.sf_mandato_exercicio
    ADD CONSTRAINT fk_sf_mandato_exercicio_motivo_afastamento FOREIGN KEY (id_sf_motivo_afastamento)
    REFERENCES senado.sf_motivo_afastamento (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_mandato_exercicio
    ADD CONSTRAINT fk_sf_mandato_exercicio_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_mandato_legislatura
    ADD CONSTRAINT fk_sf_mandato_legislatura_legislatura FOREIGN KEY (id_sf_legislatura)
    REFERENCES senado.sf_legislatura (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "FK__sf_legislatura"
    ON senado.sf_mandato_legislatura(id_sf_legislatura);


ALTER TABLE IF EXISTS senado.sf_mandato_legislatura
    ADD CONSTRAINT fk_sf_mandato_legislatura_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_remuneracao
    ADD CONSTRAINT fk_sf_remuneracao_cargo FOREIGN KEY (id_cargo)
    REFERENCES senado.sf_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sfm_id_cargo
    ON senado.sf_remuneracao(id_cargo);


ALTER TABLE IF EXISTS senado.sf_remuneracao
    ADD CONSTRAINT fk_sf_remuneracao_categoria FOREIGN KEY (id_categoria)
    REFERENCES senado.sf_categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sfm_id_categoria
    ON senado.sf_remuneracao(id_categoria);


ALTER TABLE IF EXISTS senado.sf_remuneracao
    ADD CONSTRAINT fk_sf_remuneracao_funcao FOREIGN KEY (id_simbolo_funcao)
    REFERENCES senado.sf_funcao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sfm_id_simbolo_funcao
    ON senado.sf_remuneracao(id_simbolo_funcao);


ALTER TABLE IF EXISTS senado.sf_remuneracao
    ADD CONSTRAINT fk_sf_remuneracao_lotacao FOREIGN KEY (id_lotacao)
    REFERENCES senado.sf_lotacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sfm_id_lotacao
    ON senado.sf_remuneracao(id_lotacao);


ALTER TABLE IF EXISTS senado.sf_remuneracao
    ADD CONSTRAINT fk_sf_remuneracao_referencia_cargo FOREIGN KEY (id_referencia_cargo)
    REFERENCES senado.sf_referencia_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sfm_id_referencia_cargo
    ON senado.sf_remuneracao(id_referencia_cargo);


ALTER TABLE IF EXISTS senado.sf_remuneracao
    ADD CONSTRAINT fk_sf_remuneracao_tipo_folha FOREIGN KEY (id_tipo_folha)
    REFERENCES senado.sf_tipo_folha (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sfm_id_tipo_folha
    ON senado.sf_remuneracao(id_tipo_folha);


ALTER TABLE IF EXISTS senado.sf_remuneracao
    ADD CONSTRAINT fk_sf_remuneracao_vinculo FOREIGN KEY (id_vinculo)
    REFERENCES senado.sf_vinculo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sfm_id_vinculo
    ON senado.sf_remuneracao(id_vinculo);


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_cargo FOREIGN KEY (id_cargo)
    REFERENCES senado.sf_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_categoria FOREIGN KEY (id_categoria)
    REFERENCES senado.sf_categoria (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_especialidade FOREIGN KEY (id_especialidade)
    REFERENCES senado.sf_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_funcao FOREIGN KEY (id_funcao)
    REFERENCES senado.sf_funcao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_lotacao FOREIGN KEY (id_lotacao)
    REFERENCES senado.sf_lotacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_referencia_cargo FOREIGN KEY (id_referencia_cargo)
    REFERENCES senado.sf_referencia_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_senador FOREIGN KEY (id_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT fk_sf_secretario_vinculo FOREIGN KEY (id_vinculo)
    REFERENCES senado.sf_vinculo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_secretario
    ADD CONSTRAINT sf_secretario_id_sf_situacao_fkey FOREIGN KEY (id_sf_situacao)
    REFERENCES senado.sf_situacao (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS senado.sf_senador_campeao_gasto
    ADD CONSTRAINT fk_sf_senador_campeao_gasto_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS sf_senador_campeao_gasto_pkey
    ON senado.sf_senador_campeao_gasto(id_sf_senador);


ALTER TABLE IF EXISTS senado.sf_senador_historico_academico
    ADD CONSTRAINT fk_sf_senador_historico_academico_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_senador_partido
    ADD CONSTRAINT fk_sf_senador_partido_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_senador_profissao
    ADD CONSTRAINT fk_sf_senador_profissao_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS senado.sf_senador_verba_gabinete
    ADD CONSTRAINT fk_cf_senador_verba_gabinete_senador FOREIGN KEY (id_sf_senador)
    REFERENCES senado.sf_senador (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS id_sf_senador
    ON senado.sf_senador_verba_gabinete(id_sf_senador);

END;