-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS temp.arquivo_cheksum
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(255) COLLATE pg_catalog."default" NOT NULL,
    checksum character varying(255) COLLATE pg_catalog."default",
    tamanho_bytes bigint,
    criacao timestamp(6) without time zone NOT NULL,
    atualizacao timestamp(6) without time zone NOT NULL,
    verificacao timestamp(6) without time zone NOT NULL,
    valor_total numeric(20, 6) NOT NULL,
    divergencia numeric(10, 2) NOT NULL,
    revisado boolean NOT NULL,
    CONSTRAINT arquivo_cheksum_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS temp.cf_deputado_funcionario_temp
(
    id_cf_deputado integer,
    chave character varying(45) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    grupo_funcional character varying(100) COLLATE pg_catalog."default" NOT NULL,
    nivel character varying(100) COLLATE pg_catalog."default",
    periodo_de date NOT NULL,
    periodo_ate date
);

CREATE TABLE IF NOT EXISTS temp.cf_despesa_temp
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_deputado bigint,
    nome_parlamentar character varying(100) COLLATE pg_catalog."default",
    numero_carteira_parlamentar integer,
    legislatura integer,
    sigla_uf character varying(2) COLLATE pg_catalog."default",
    sigla_partido character varying(20) COLLATE pg_catalog."default",
    codigo_legislatura integer,
    numero_sub_cota integer,
    descricao character varying(100) COLLATE pg_catalog."default",
    numero_especificacao_sub_cota integer,
    descricao_especificacao character varying(100) COLLATE pg_catalog."default",
    fornecedor character varying(255) COLLATE pg_catalog."default",
    cnpj_cpf character varying(14) COLLATE pg_catalog."default",
    numero character varying(50) COLLATE pg_catalog."default",
    tipo_documento character varying(10) COLLATE pg_catalog."default",
    data_emissao date,
    valor_documento numeric(10, 2),
    valor_glosa numeric(10, 2),
    valor_liquido numeric(10, 2),
    mes numeric(2, 0),
    ano numeric(4, 0),
    parcela numeric(3, 0),
    passageiro character varying(100) COLLATE pg_catalog."default",
    trecho character varying(100) COLLATE pg_catalog."default",
    lote integer,
    ressarcimento integer,
    id_documento character varying(20) COLLATE pg_catalog."default",
    restituicao numeric(10, 2),
    data_pagamento_restituicao date,
    numero_deputado_id integer,
    cpf character varying(15) COLLATE pg_catalog."default",
    url_documento character varying(255) COLLATE pg_catalog."default",
    hash bytea,
    id_fornecedor bigint,
    CONSTRAINT cf_despesa_temp_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS temp.cf_funcionario_temp
(
    chave character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nome character varying(255) COLLATE pg_catalog."default",
    categoria_funcional character varying(255) COLLATE pg_catalog."default",
    cargo character varying(255) COLLATE pg_catalog."default",
    nivel character varying(255) COLLATE pg_catalog."default",
    funcao_comissionada character varying(255) COLLATE pg_catalog."default",
    area_atuacao character varying(255) COLLATE pg_catalog."default",
    local_trabalho character varying(255) COLLATE pg_catalog."default",
    situacao character varying(255) COLLATE pg_catalog."default",
    data_designacao_funcao date,
    CONSTRAINT cf_funcionario_temp_pkey PRIMARY KEY (chave)
);

COMMENT ON COLUMN temp.cf_funcionario_temp.categoria_funcional
    IS 'Categoria funcional';

COMMENT ON COLUMN temp.cf_funcionario_temp.cargo
    IS 'Cargo';

COMMENT ON COLUMN temp.cf_funcionario_temp.nivel
    IS 'Nível';

COMMENT ON COLUMN temp.cf_funcionario_temp.funcao_comissionada
    IS 'Função comissionada';

COMMENT ON COLUMN temp.cf_funcionario_temp.area_atuacao
    IS 'Área de atuação';

COMMENT ON COLUMN temp.cf_funcionario_temp.local_trabalho
    IS 'Local de trabalho';

COMMENT ON COLUMN temp.cf_funcionario_temp.situacao
    IS 'Situação';

COMMENT ON COLUMN temp.cf_funcionario_temp.data_designacao_funcao
    IS 'Data da designação da função';

CREATE TABLE IF NOT EXISTS temp.cf_mandato_temp
(
    "ideCadastro" integer,
    "numLegislatura" integer,
    "nomeParlamentar" character varying(45) COLLATE pg_catalog."default",
    "Sexo" character varying(45) COLLATE pg_catalog."default",
    "Profissao" character varying(255) COLLATE pg_catalog."default",
    "LegendaPartidoEleito" character(10) COLLATE pg_catalog."default",
    "UFEleito" character(2) COLLATE pg_catalog."default",
    "Condicao" character varying(45) COLLATE pg_catalog."default",
    "SituacaoMandato" character varying(45) COLLATE pg_catalog."default",
    "Matricula" integer,
    "Gabinete" character varying(45) COLLATE pg_catalog."default",
    "Anexo" character varying(45) COLLATE pg_catalog."default",
    "Fone" character varying(45) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.cf_remuneracao_temp
(
    id integer,
    ano_mes integer,
    cargo character varying(255) COLLATE pg_catalog."default",
    grupo_funcional character varying(255) COLLATE pg_catalog."default",
    tipo_folha character varying(255) COLLATE pg_catalog."default",
    admissao integer,
    remun_basica numeric(10, 2),
    vant_pessoais numeric(10, 2),
    func_comissionada numeric(10, 2),
    grat_natalina numeric(10, 2),
    ferias numeric(10, 2),
    outras_eventuais numeric(10, 2),
    abono_permanencia numeric(10, 2),
    reversao_teto_const numeric(10, 2),
    previdencia numeric(10, 2),
    imposto_renda numeric(10, 2),
    rem_liquida numeric(10, 2),
    diarias numeric(10, 2),
    auxilios numeric(10, 2),
    vant_indenizatorias numeric(10, 2)
);

COMMENT ON COLUMN temp.cf_remuneracao_temp.cargo
    IS 'Cargo Individualizado do Servidor';

COMMENT ON COLUMN temp.cf_remuneracao_temp.grupo_funcional
    IS 'Grupo Funcional';

COMMENT ON COLUMN temp.cf_remuneracao_temp.tipo_folha
    IS 'Folha de Pagamento';

COMMENT ON COLUMN temp.cf_remuneracao_temp.admissao
    IS 'Ano Ingresso';

COMMENT ON COLUMN temp.cf_remuneracao_temp.remun_basica
    IS 'Remuneração Fixa';

COMMENT ON COLUMN temp.cf_remuneracao_temp.vant_pessoais
    IS 'Vantagens de Natureza Pessoal';

COMMENT ON COLUMN temp.cf_remuneracao_temp.func_comissionada
    IS 'Função ou Cargo em Comissão';

COMMENT ON COLUMN temp.cf_remuneracao_temp.grat_natalina
    IS 'Gratificação Natalina';

COMMENT ON COLUMN temp.cf_remuneracao_temp.ferias
    IS 'Férias (1/3 Constitucional)';

COMMENT ON COLUMN temp.cf_remuneracao_temp.outras_eventuais
    IS 'Outras Remunerações Eventuais/Provisórias(*)';

COMMENT ON COLUMN temp.cf_remuneracao_temp.abono_permanencia
    IS 'Abono de Permanência';

COMMENT ON COLUMN temp.cf_remuneracao_temp.reversao_teto_const
    IS 'Redutor Constitucional';

COMMENT ON COLUMN temp.cf_remuneracao_temp.previdencia
    IS 'Constribuição Previdenciária';

COMMENT ON COLUMN temp.cf_remuneracao_temp.imposto_renda
    IS 'Imposto de Renda';

COMMENT ON COLUMN temp.cf_remuneracao_temp.rem_liquida
    IS 'Remuneração Após Descontos Obrigatórios';

COMMENT ON COLUMN temp.cf_remuneracao_temp.diarias
    IS 'Diárias';

COMMENT ON COLUMN temp.cf_remuneracao_temp.auxilios
    IS 'Auxílios';

COMMENT ON COLUMN temp.cf_remuneracao_temp.vant_indenizatorias
    IS 'Vantagens Indenizatórias';

CREATE TABLE IF NOT EXISTS temp.cf_secretario_remuneracao_temp
(
    id_cf_secretario character varying(255) COLLATE pg_catalog."default" NOT NULL,
    referencia character varying(255) COLLATE pg_catalog."default",
    descricao character varying(255) COLLATE pg_catalog."default",
    remuneracao_fixa numeric(10, 2),
    vantagens_natureza_pessoal numeric(10, 2),
    funcao_ou_cargo_em_comissao numeric(10, 2),
    gratificacao_natalina numeric(10, 2),
    ferias numeric(10, 2),
    outras_remuneracoes numeric(10, 2),
    valor_bruto numeric(10, 2),
    abono_permanencia numeric(10, 2),
    redutor_constitucional numeric(10, 2),
    contribuicao_previdenciaria numeric(10, 2),
    imposto_renda numeric(10, 2),
    valor_liquido numeric(10, 2),
    valor_diarias numeric(10, 2),
    valor_auxilios numeric(10, 2),
    valor_vantagens numeric(10, 2),
    valor_outros numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS temp.cl_deputado_de_para
(
    id bigint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_estado smallint NOT NULL
);

CREATE TABLE IF NOT EXISTS temp.cl_despesa_temp
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    id_cl_deputado integer,
    nome character varying(255) COLLATE pg_catalog."default",
    nome_civil character varying(255) COLLATE pg_catalog."default",
    cpf character varying(50) COLLATE pg_catalog."default",
    empresa character varying(255) COLLATE pg_catalog."default",
    cnpj_cpf character varying(20) COLLATE pg_catalog."default",
    data_emissao date,
    tipo_verba character varying(100) COLLATE pg_catalog."default",
    despesa_tipo character varying(400) COLLATE pg_catalog."default",
    documento character varying(100) COLLATE pg_catalog."default",
    observacao character varying(8000) COLLATE pg_catalog."default",
    valor numeric(10, 2) NOT NULL,
    ano smallint NOT NULL,
    mes smallint,
    favorecido character varying(200) COLLATE pg_catalog."default",
    hash bytea,
    CONSTRAINT cl_despesa_temp_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS temp.cl_empenho_temp
(
    id bigint NOT NULL,
    nome_favorecido character varying(100) COLLATE pg_catalog."default" NOT NULL,
    id_cl_deputado bigint NOT NULL,
    nome_deputado character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cnpj_cpf character varying(100) COLLATE pg_catalog."default" NOT NULL,
    numero_empenho character varying(100) COLLATE pg_catalog."default" NOT NULL,
    data date NOT NULL,
    competencia date NOT NULL,
    valor_empenhado numeric(10, 2) NOT NULL,
    valor_pago numeric(10, 2) NOT NULL,
    CONSTRAINT cl_empenho_temp_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS temp.fornecedor_de_para
(
    cnpj_incorreto character varying(20) COLLATE pg_catalog."default",
    id_fornecedor_incorreto bigint,
    nome character varying(255) COLLATE pg_catalog."default",
    id_fornecedor_correto bigint,
    cnpj_correto character varying(15) COLLATE pg_catalog."default",
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    CONSTRAINT fornecedor_de_para_pkey PRIMARY KEY (id),
    CONSTRAINT fornecedor_de_para_cnpj_incorreto_nome_key UNIQUE (cnpj_incorreto, nome)
);

CREATE TABLE IF NOT EXISTS temp.partido_de_para
(
    id_partido smallint NOT NULL,
    nome character varying(100) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.sf_despesa_temp
(
    ano numeric(4, 0),
    mes numeric(2, 0),
    senador character varying(255) COLLATE pg_catalog."default",
    tipo_despesa character varying(255) COLLATE pg_catalog."default",
    cnpj_cpf character varying(14) COLLATE pg_catalog."default",
    fornecedor character varying(255) COLLATE pg_catalog."default",
    documento character varying(50) COLLATE pg_catalog."default",
    data timestamp(6) without time zone,
    detalhamento text COLLATE pg_catalog."default",
    valor_reembolsado numeric(10, 2),
    cod_documento numeric(20, 0),
    hash bytea,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT sf_despesa_temp_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS temp.sf_remuneracao_temp
(
    ano_mes integer,
    vinculo character varying(255) COLLATE pg_catalog."default",
    categoria character varying(255) COLLATE pg_catalog."default",
    cargo character varying(255) COLLATE pg_catalog."default",
    referencia_cargo character varying(255) COLLATE pg_catalog."default",
    simbolo_funcao character varying(255) COLLATE pg_catalog."default",
    lotacao_exercicio character varying(255) COLLATE pg_catalog."default",
    tipo_folha character varying(255) COLLATE pg_catalog."default",
    admissao integer,
    remun_basica numeric(10, 2),
    vant_pessoais numeric(10, 2),
    func_comissionada numeric(10, 2),
    grat_natalina numeric(10, 2),
    horas_extras numeric(10, 2),
    outras_eventuais numeric(10, 2),
    abono_permanencia numeric(10, 2),
    reversao_teto_const numeric(10, 2),
    imposto_renda numeric(10, 2),
    previdencia numeric(10, 2),
    faltas numeric(10, 2),
    rem_liquida numeric(10, 2),
    diarias numeric(10, 2),
    auxilios numeric(10, 2),
    vant_indenizatorias numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS temp.sf_secretario_temp
(
    id bigint,
    id_senador bigint,
    nome character varying(255) COLLATE pg_catalog."default",
    funcao character varying(10) COLLATE pg_catalog."default",
    nome_funcao character varying(255) COLLATE pg_catalog."default",
    vinculo character varying(255) COLLATE pg_catalog."default",
    situacao character varying(255) COLLATE pg_catalog."default",
    admissao integer,
    cargo character varying(100) COLLATE pg_catalog."default",
    padrao character varying(10) COLLATE pg_catalog."default",
    especialidade character varying(255) COLLATE pg_catalog."default",
    lotacao character varying(255) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.tse_candidato
(
    "DT_GERACAO" text COLLATE pg_catalog."default",
    "HH_GERACAO" text COLLATE pg_catalog."default",
    "ANO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "NM_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "NR_TURNO" text COLLATE pg_catalog."default",
    "CD_ELEICAO" text COLLATE pg_catalog."default",
    "DS_ELEICAO" text COLLATE pg_catalog."default",
    "DT_ELEICAO" text COLLATE pg_catalog."default",
    "TP_ABRANGENCIA" text COLLATE pg_catalog."default",
    "SG_UF" text COLLATE pg_catalog."default",
    "SG_UE" text COLLATE pg_catalog."default",
    "NM_UE" text COLLATE pg_catalog."default",
    "CD_CARGO" text COLLATE pg_catalog."default",
    "DS_CARGO" text COLLATE pg_catalog."default",
    "SQ_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CANDIDATO" text COLLATE pg_catalog."default",
    "NM_CANDIDATO" text COLLATE pg_catalog."default",
    "NM_URNA_CANDIDATO" text COLLATE pg_catalog."default",
    "NM_SOCIAL_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CPF_CANDIDATO" text COLLATE pg_catalog."default",
    "NM_EMAIL" text COLLATE pg_catalog."default",
    "CD_SITUACAO_CANDIDATURA" text COLLATE pg_catalog."default",
    "DS_SITUACAO_CANDIDATURA" text COLLATE pg_catalog."default",
    "CD_DETALHE_SITUACAO_CAND" text COLLATE pg_catalog."default",
    "DS_DETALHE_SITUACAO_CAND" text COLLATE pg_catalog."default",
    "TP_AGREMIACAO" text COLLATE pg_catalog."default",
    "NR_PARTIDO" text COLLATE pg_catalog."default",
    "SG_PARTIDO" text COLLATE pg_catalog."default",
    "NM_PARTIDO" text COLLATE pg_catalog."default",
    "SQ_COLIGACAO" text COLLATE pg_catalog."default",
    "NM_COLIGACAO" text COLLATE pg_catalog."default",
    "DS_COMPOSICAO_COLIGACAO" text COLLATE pg_catalog."default",
    "CD_NACIONALIDADE" text COLLATE pg_catalog."default",
    "DS_NACIONALIDADE" text COLLATE pg_catalog."default",
    "SG_UF_NASCIMENTO" text COLLATE pg_catalog."default",
    "CD_MUNICIPIO_NASCIMENTO" text COLLATE pg_catalog."default",
    "NM_MUNICIPIO_NASCIMENTO" text COLLATE pg_catalog."default",
    "DT_NASCIMENTO" text COLLATE pg_catalog."default",
    "NR_IDADE_DATA_POSSE" text COLLATE pg_catalog."default",
    "NR_TITULO_ELEITORAL_CANDIDATO" text COLLATE pg_catalog."default",
    "CD_GENERO" text COLLATE pg_catalog."default",
    "DS_GENERO" text COLLATE pg_catalog."default",
    "CD_GRAU_INSTRUCAO" text COLLATE pg_catalog."default",
    "DS_GRAU_INSTRUCAO" text COLLATE pg_catalog."default",
    "CD_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "DS_ESTADO_CIVIL" text COLLATE pg_catalog."default",
    "CD_COR_RACA" text COLLATE pg_catalog."default",
    "DS_COR_RACA" text COLLATE pg_catalog."default",
    "CD_OCUPACAO" text COLLATE pg_catalog."default",
    "DS_OCUPACAO" text COLLATE pg_catalog."default",
    "VR_DESPESA_MAX_CAMPANHA" text COLLATE pg_catalog."default",
    "CD_SIT_TOT_TURNO" text COLLATE pg_catalog."default",
    "DS_SIT_TOT_TURNO" text COLLATE pg_catalog."default",
    "ST_REELEICAO" text COLLATE pg_catalog."default",
    "ST_DECLARAR_BENS" text COLLATE pg_catalog."default",
    "NR_PROTOCOLO_CANDIDATURA" text COLLATE pg_catalog."default",
    "NR_PROCESSO" text COLLATE pg_catalog."default",
    "CD_SITUACAO_CANDIDATO_PLEITO" text COLLATE pg_catalog."default",
    "DS_SITUACAO_CANDIDATO_PLEITO" text COLLATE pg_catalog."default",
    "CD_SITUACAO_CANDIDATO_URNA" text COLLATE pg_catalog."default",
    "DS_SITUACAO_CANDIDATO_URNA" text COLLATE pg_catalog."default",
    "ST_CANDIDATO_INSERIDO_URNA" text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.tse_despesa_contratada
(
    "DT_GERACAO" text COLLATE pg_catalog."default",
    "HH_GERACAO" text COLLATE pg_catalog."default",
    "ANO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "NM_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_ELEICAO" text COLLATE pg_catalog."default",
    "DS_ELEICAO" text COLLATE pg_catalog."default",
    "DT_ELEICAO" text COLLATE pg_catalog."default",
    "ST_TURNO" text COLLATE pg_catalog."default",
    "TP_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "DT_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "SQ_PRESTADOR_CONTAS" text COLLATE pg_catalog."default",
    "SG_UF" text COLLATE pg_catalog."default",
    "SG_UE" text COLLATE pg_catalog."default",
    "NM_UE" text COLLATE pg_catalog."default",
    "NR_CNPJ_PRESTADOR_CONTA" text COLLATE pg_catalog."default",
    "CD_CARGO" text COLLATE pg_catalog."default",
    "DS_CARGO" text COLLATE pg_catalog."default",
    "SQ_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CANDIDATO" text COLLATE pg_catalog."default",
    "NM_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CPF_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CPF_VICE_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_PARTIDO" text COLLATE pg_catalog."default",
    "SG_PARTIDO" text COLLATE pg_catalog."default",
    "NM_PARTIDO" text COLLATE pg_catalog."default",
    "CD_TIPO_FORNECEDOR" text COLLATE pg_catalog."default",
    "DS_TIPO_FORNECEDOR" text COLLATE pg_catalog."default",
    "CD_CNAE_FORNECEDOR" text COLLATE pg_catalog."default",
    "DS_CNAE_FORNECEDOR" text COLLATE pg_catalog."default",
    "NR_CPF_CNPJ_FORNECEDOR" text COLLATE pg_catalog."default",
    "NM_FORNECEDOR" text COLLATE pg_catalog."default",
    "NM_FORNECEDOR_RFB" text COLLATE pg_catalog."default",
    "CD_ESFERA_PART_FORNECEDOR" text COLLATE pg_catalog."default",
    "DS_ESFERA_PART_FORNECEDOR" text COLLATE pg_catalog."default",
    "SG_UF_FORNECEDOR" text COLLATE pg_catalog."default",
    "CD_MUNICIPIO_FORNECEDOR" text COLLATE pg_catalog."default",
    "NM_MUNICIPIO_FORNECEDOR" text COLLATE pg_catalog."default",
    "SQ_CANDIDATO_FORNECEDOR" text COLLATE pg_catalog."default",
    "NR_CANDIDATO_FORNECEDOR" text COLLATE pg_catalog."default",
    "CD_CARGO_FORNECEDOR" text COLLATE pg_catalog."default",
    "DS_CARGO_FORNECEDOR" text COLLATE pg_catalog."default",
    "NR_PARTIDO_FORNECEDOR" text COLLATE pg_catalog."default",
    "SG_PARTIDO_FORNECEDOR" text COLLATE pg_catalog."default",
    "NM_PARTIDO_FORNECEDOR" text COLLATE pg_catalog."default",
    "DS_TIPO_DOCUMENTO" text COLLATE pg_catalog."default",
    "NR_DOCUMENTO" text COLLATE pg_catalog."default",
    "CD_ORIGEM_DESPESA" text COLLATE pg_catalog."default",
    "DS_ORIGEM_DESPESA" text COLLATE pg_catalog."default",
    "SQ_DESPESA" text COLLATE pg_catalog."default",
    "DT_DESPESA" text COLLATE pg_catalog."default",
    "DS_DESPESA" text COLLATE pg_catalog."default",
    "VR_DESPESA_CONTRATADA" text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.tse_despesa_paga
(
    "DT_GERACAO" text COLLATE pg_catalog."default",
    "HH_GERACAO" text COLLATE pg_catalog."default",
    "ANO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "NM_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_ELEICAO" text COLLATE pg_catalog."default",
    "DS_ELEICAO" text COLLATE pg_catalog."default",
    "DT_ELEICAO" text COLLATE pg_catalog."default",
    "ST_TURNO" text COLLATE pg_catalog."default",
    "TP_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "DT_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "SQ_PRESTADOR_CONTAS" text COLLATE pg_catalog."default",
    "SG_UF" text COLLATE pg_catalog."default",
    "DS_TIPO_DOCUMENTO" text COLLATE pg_catalog."default",
    "NR_DOCUMENTO" text COLLATE pg_catalog."default",
    "CD_FONTE_DESPESA" text COLLATE pg_catalog."default",
    "DS_FONTE_DESPESA" text COLLATE pg_catalog."default",
    "CD_ORIGEM_DESPESA" text COLLATE pg_catalog."default",
    "DS_ORIGEM_DESPESA" text COLLATE pg_catalog."default",
    "CD_NATUREZA_DESPESA" text COLLATE pg_catalog."default",
    "DS_NATUREZA_DESPESA" text COLLATE pg_catalog."default",
    "CD_ESPECIE_RECURSO" text COLLATE pg_catalog."default",
    "DS_ESPECIE_RECURSO" text COLLATE pg_catalog."default",
    "SQ_DESPESA" text COLLATE pg_catalog."default",
    "SQ_PARCELAMENTO_DESPESA" text COLLATE pg_catalog."default",
    "DT_PAGTO_DESPESA" text COLLATE pg_catalog."default",
    "DS_DESPESA" text COLLATE pg_catalog."default",
    "VR_PAGTO_DESPESA" text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.tse_receita
(
    "DT_GERACAO" text COLLATE pg_catalog."default",
    "HH_GERACAO" text COLLATE pg_catalog."default",
    "ANO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "NM_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_ELEICAO" text COLLATE pg_catalog."default",
    "DS_ELEICAO" text COLLATE pg_catalog."default",
    "DT_ELEICAO" text COLLATE pg_catalog."default",
    "ST_TURNO" text COLLATE pg_catalog."default",
    "TP_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "DT_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "SQ_PRESTADOR_CONTAS" text COLLATE pg_catalog."default",
    "SG_UF" text COLLATE pg_catalog."default",
    "SG_UE" text COLLATE pg_catalog."default",
    "NM_UE" text COLLATE pg_catalog."default",
    "NR_CNPJ_PRESTADOR_CONTA" text COLLATE pg_catalog."default",
    "CD_CARGO" text COLLATE pg_catalog."default",
    "DS_CARGO" text COLLATE pg_catalog."default",
    "SQ_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CANDIDATO" text COLLATE pg_catalog."default",
    "NM_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CPF_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_CPF_VICE_CANDIDATO" text COLLATE pg_catalog."default",
    "NR_PARTIDO" text COLLATE pg_catalog."default",
    "SG_PARTIDO" text COLLATE pg_catalog."default",
    "NM_PARTIDO" text COLLATE pg_catalog."default",
    "CD_FONTE_RECEITA" text COLLATE pg_catalog."default",
    "DS_FONTE_RECEITA" text COLLATE pg_catalog."default",
    "CD_ORIGEM_RECEITA" text COLLATE pg_catalog."default",
    "DS_ORIGEM_RECEITA" text COLLATE pg_catalog."default",
    "CD_NATUREZA_RECEITA" text COLLATE pg_catalog."default",
    "DS_NATUREZA_RECEITA" text COLLATE pg_catalog."default",
    "CD_ESPECIE_RECEITA" text COLLATE pg_catalog."default",
    "DS_ESPECIE_RECEITA" text COLLATE pg_catalog."default",
    "CD_CNAE_DOADOR" text COLLATE pg_catalog."default",
    "DS_CNAE_DOADOR" text COLLATE pg_catalog."default",
    "NR_CPF_CNPJ_DOADOR" text COLLATE pg_catalog."default",
    "NM_DOADOR" text COLLATE pg_catalog."default",
    "NM_DOADOR_RFB" text COLLATE pg_catalog."default",
    "CD_ESFERA_PARTIDARIA_DOADOR" text COLLATE pg_catalog."default",
    "DS_ESFERA_PARTIDARIA_DOADOR" text COLLATE pg_catalog."default",
    "SG_UF_DOADOR" text COLLATE pg_catalog."default",
    "CD_MUNICIPIO_DOADOR" text COLLATE pg_catalog."default",
    "NM_MUNICIPIO_DOADOR" text COLLATE pg_catalog."default",
    "SQ_CANDIDATO_DOADOR" text COLLATE pg_catalog."default",
    "NR_CANDIDATO_DOADOR" text COLLATE pg_catalog."default",
    "CD_CARGO_CANDIDATO_DOADOR" text COLLATE pg_catalog."default",
    "DS_CARGO_CANDIDATO_DOADOR" text COLLATE pg_catalog."default",
    "NR_PARTIDO_DOADOR" text COLLATE pg_catalog."default",
    "SG_PARTIDO_DOADOR" text COLLATE pg_catalog."default",
    "NM_PARTIDO_DOADOR" text COLLATE pg_catalog."default",
    "NR_RECIBO_DOACAO" text COLLATE pg_catalog."default",
    "NR_DOCUMENTO_DOACAO" text COLLATE pg_catalog."default",
    "SQ_RECEITA" text COLLATE pg_catalog."default",
    "DT_RECEITA" text COLLATE pg_catalog."default",
    "DS_RECEITA" text COLLATE pg_catalog."default",
    "VR_RECEITA" text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.tse_receita_doador_originario
(
    "DT_GERACAO" text COLLATE pg_catalog."default",
    "HH_GERACAO" text COLLATE pg_catalog."default",
    "ANO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "NM_TIPO_ELEICAO" text COLLATE pg_catalog."default",
    "CD_ELEICAO" text COLLATE pg_catalog."default",
    "DS_ELEICAO" text COLLATE pg_catalog."default",
    "DT_ELEICAO" text COLLATE pg_catalog."default",
    "ST_TURNO" text COLLATE pg_catalog."default",
    "TP_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "DT_PRESTACAO_CONTAS" text COLLATE pg_catalog."default",
    "SQ_PRESTADOR_CONTAS" text COLLATE pg_catalog."default",
    "SG_UF" text COLLATE pg_catalog."default",
    "NR_CPF_CNPJ_DOADOR_ORIGINARIO" text COLLATE pg_catalog."default",
    "NM_DOADOR_ORIGINARIO" text COLLATE pg_catalog."default",
    "NM_DOADOR_ORIGINARIO_RFB" text COLLATE pg_catalog."default",
    "TP_DOADOR_ORIGINARIO" text COLLATE pg_catalog."default",
    "CD_CNAE_DOADOR_ORIGINARIO" text COLLATE pg_catalog."default",
    "DS_CNAE_DOADOR_ORIGINARIO" text COLLATE pg_catalog."default",
    "SQ_RECEITA" text COLLATE pg_catalog."default",
    "DT_RECEITA" text COLLATE pg_catalog."default",
    "DS_RECEITA" text COLLATE pg_catalog."default",
    "VR_RECEITA" text COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS temp.x_cl_despesa_bkp
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_cl_deputado bigint NOT NULL,
    id_cl_despesa_tipo bigint,
    id_cl_despesa_especificacao bigint,
    id_fornecedor bigint,
    data_emissao date,
    ano_mes integer,
    numero_documento character varying(50) COLLATE pg_catalog."default",
    valor_liquido numeric(10, 2) NOT NULL,
    favorecido character varying(200) COLLATE pg_catalog."default",
    observacao character varying(8000) COLLATE pg_catalog."default",
    hash bytea,
    CONSTRAINT cl_despesa_copy1_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS temp.x_cl_despesa_especificacao
(
    id integer NOT NULL,
    id_cl_despesa_tipo integer,
    descricao character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT cl_despesa_especificacao_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS temp.x_cl_despesa_resumo_temp
(
    id_deputado bigint,
    ano integer,
    mes integer,
    valor numeric(10, 2),
    valor_ajustado numeric(10, 2)
);

CREATE TABLE IF NOT EXISTS temp.x_fornecedor_correcao
(
    cnpj_cpf character varying(15) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    cnpj_cpf_correto character(15) COLLATE pg_catalog."default"
);
END;