-- This script was generated by the ERD tool in pgAdmin 4.
BEGIN;


CREATE TABLE IF NOT EXISTS tse.tse_eleicao
(
    id bigint,
    descricao character varying(50) COLLATE pg_catalog."default",
    data date,
    turno character varying(50) COLLATE pg_catalog."default",
    tipo character varying(50) COLLATE pg_catalog."default",
    abrangencia character varying(50) COLLATE pg_catalog."default"
);

COMMENT ON TABLE tse.tse_eleicao
    IS 'CD_ELEICAO, DS_ELEICAO, DT_ELEICAO, NM_TIPO_ELEICAO, NR_TURNO, TP_ABRANGENCIA';

CREATE TABLE IF NOT EXISTS tse.tse_eleicao_candidato
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    cpf character varying(11) COLLATE pg_catalog."default",
    nome character varying(255) COLLATE pg_catalog."default",
    email character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tse_eleicao_candidato_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tse.tse_eleicao_candidatura
(
    numero bigint NOT NULL,
    cargo smallint NOT NULL,
    ano bigint NOT NULL,
    id_eleicao_candidato integer,
    id_eleicao_candidato_vice integer,
    sigla_partido character varying(50) COLLATE pg_catalog."default",
    sigla_partido_vice character varying(50) COLLATE pg_catalog."default",
    nome_urna character varying(255) COLLATE pg_catalog."default",
    nome_urna_vice character varying(255) COLLATE pg_catalog."default",
    sequencia character varying(50) COLLATE pg_catalog."default",
    sequencia_vice character varying(50) COLLATE pg_catalog."default",
    sigla_estado character(2) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tse_eleicao_candidatura_pkey PRIMARY KEY (numero, cargo, ano, sigla_estado)
);

CREATE TABLE IF NOT EXISTS tse.tse_eleicao_cargo
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nome character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT tse_eleicao_cargo_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tse.tse_eleicao_doacao
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    id_eleicao_cargo bigint,
    id_eleicao_candidadto bigint,
    ano_eleicao numeric(4, 0),
    num_documento character varying(50) COLLATE pg_catalog."default",
    cnpj_cpf_doador character varying(14) COLLATE pg_catalog."default",
    raiz_cnpj_cpf_doador character varying(14) COLLATE pg_catalog."default",
    data_receita date,
    valor_receita numeric(10, 2),
    CONSTRAINT tse_eleicao_doacao_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS tse.tse_eleicao_candidatura
    ADD CONSTRAINT fk_tse_eleicao_candidatura_candidato FOREIGN KEY (id_eleicao_candidato)
    REFERENCES tse.tse_eleicao_candidato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tse.tse_eleicao_candidatura
    ADD CONSTRAINT fk_tse_eleicao_candidatura_candidato_vice FOREIGN KEY (id_eleicao_candidato_vice)
    REFERENCES tse.tse_eleicao_candidato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tse.tse_eleicao_candidatura
    ADD CONSTRAINT fk_tse_eleicao_candidatura_cargo FOREIGN KEY (cargo)
    REFERENCES tse.tse_eleicao_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tse.tse_eleicao_doacao
    ADD CONSTRAINT fk_tse_eleicao_doacao_candidato FOREIGN KEY (id_eleicao_candidadto)
    REFERENCES tse.tse_eleicao_candidato (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS tse.tse_eleicao_doacao
    ADD CONSTRAINT fk_tse_eleicao_doacao_cargo FOREIGN KEY (id_eleicao_cargo)
    REFERENCES tse.tse_eleicao_cargo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;