//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OPS.ImportacaoDados.CamaraWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeputadosSoap", Namespace="http://www.camara.gov.br/SitCamaraWS/Deputados")]
    public partial class Deputados : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObterDeputadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterPartidosCDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterPartidosBlocoCDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterDetalhesDeputadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterLideresBancadasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterIdCadastroOrcamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Deputados() {
            this.Url = global::OPS.ImportacaoDados.Properties.Settings.Default.OPS_ImportacaoDados_CamaraWS_Deputados;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObterDeputadosCompletedEventHandler ObterDeputadosCompleted;
        
        /// <remarks/>
        public event ObterPartidosCDCompletedEventHandler ObterPartidosCDCompleted;
        
        /// <remarks/>
        public event ObterPartidosBlocoCDCompletedEventHandler ObterPartidosBlocoCDCompleted;
        
        /// <remarks/>
        public event ObterDetalhesDeputadoCompletedEventHandler ObterDetalhesDeputadoCompleted;
        
        /// <remarks/>
        public event ObterLideresBancadasCompletedEventHandler ObterLideresBancadasCompleted;
        
        /// <remarks/>
        public event ObterIdCadastroOrcamentoCompletedEventHandler ObterIdCadastroOrcamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDeputados", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ObterDeputados() {
            object[] results = this.Invoke("ObterDeputados", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ObterDeputadosAsync() {
            this.ObterDeputadosAsync(null);
        }
        
        /// <remarks/>
        public void ObterDeputadosAsync(object userState) {
            if ((this.ObterDeputadosOperationCompleted == null)) {
                this.ObterDeputadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterDeputadosOperationCompleted);
            }
            this.InvokeAsync("ObterDeputados", new object[0], this.ObterDeputadosOperationCompleted, userState);
        }
        
        private void OnObterDeputadosOperationCompleted(object arg) {
            if ((this.ObterDeputadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterDeputadosCompleted(this, new ObterDeputadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosCD", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ObterPartidosCD() {
            object[] results = this.Invoke("ObterPartidosCD", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ObterPartidosCDAsync() {
            this.ObterPartidosCDAsync(null);
        }
        
        /// <remarks/>
        public void ObterPartidosCDAsync(object userState) {
            if ((this.ObterPartidosCDOperationCompleted == null)) {
                this.ObterPartidosCDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterPartidosCDOperationCompleted);
            }
            this.InvokeAsync("ObterPartidosCD", new object[0], this.ObterPartidosCDOperationCompleted, userState);
        }
        
        private void OnObterPartidosCDOperationCompleted(object arg) {
            if ((this.ObterPartidosCDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterPartidosCDCompleted(this, new ObterPartidosCDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosBlocoCD", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ObterPartidosBlocoCD(string idBloco, string numLegislatura) {
            object[] results = this.Invoke("ObterPartidosBlocoCD", new object[] {
                        idBloco,
                        numLegislatura});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ObterPartidosBlocoCDAsync(string idBloco, string numLegislatura) {
            this.ObterPartidosBlocoCDAsync(idBloco, numLegislatura, null);
        }
        
        /// <remarks/>
        public void ObterPartidosBlocoCDAsync(string idBloco, string numLegislatura, object userState) {
            if ((this.ObterPartidosBlocoCDOperationCompleted == null)) {
                this.ObterPartidosBlocoCDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterPartidosBlocoCDOperationCompleted);
            }
            this.InvokeAsync("ObterPartidosBlocoCD", new object[] {
                        idBloco,
                        numLegislatura}, this.ObterPartidosBlocoCDOperationCompleted, userState);
        }
        
        private void OnObterPartidosBlocoCDOperationCompleted(object arg) {
            if ((this.ObterPartidosBlocoCDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterPartidosBlocoCDCompleted(this, new ObterPartidosBlocoCDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDetalhesDeputado", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ObterDetalhesDeputado(string ideCadastro, string numLegislatura) {
            object[] results = this.Invoke("ObterDetalhesDeputado", new object[] {
                        ideCadastro,
                        numLegislatura});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ObterDetalhesDeputadoAsync(string ideCadastro, string numLegislatura) {
            this.ObterDetalhesDeputadoAsync(ideCadastro, numLegislatura, null);
        }
        
        /// <remarks/>
        public void ObterDetalhesDeputadoAsync(string ideCadastro, string numLegislatura, object userState) {
            if ((this.ObterDetalhesDeputadoOperationCompleted == null)) {
                this.ObterDetalhesDeputadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterDetalhesDeputadoOperationCompleted);
            }
            this.InvokeAsync("ObterDetalhesDeputado", new object[] {
                        ideCadastro,
                        numLegislatura}, this.ObterDetalhesDeputadoOperationCompleted, userState);
        }
        
        private void OnObterDetalhesDeputadoOperationCompleted(object arg) {
            if ((this.ObterDetalhesDeputadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterDetalhesDeputadoCompleted(this, new ObterDetalhesDeputadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/Deputados/ObterLideresBancadas", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ObterLideresBancadas() {
            object[] results = this.Invoke("ObterLideresBancadas", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ObterLideresBancadasAsync() {
            this.ObterLideresBancadasAsync(null);
        }
        
        /// <remarks/>
        public void ObterLideresBancadasAsync(object userState) {
            if ((this.ObterLideresBancadasOperationCompleted == null)) {
                this.ObterLideresBancadasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterLideresBancadasOperationCompleted);
            }
            this.InvokeAsync("ObterLideresBancadas", new object[0], this.ObterLideresBancadasOperationCompleted, userState);
        }
        
        private void OnObterLideresBancadasOperationCompleted(object arg) {
            if ((this.ObterLideresBancadasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterLideresBancadasCompleted(this, new ObterLideresBancadasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.camara.gov.br/SitCamaraWS/Deputados/ObterIdCadastroOrcamento", RequestNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", ResponseNamespace="http://www.camara.gov.br/SitCamaraWS/Deputados", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode ObterIdCadastroOrcamento() {
            object[] results = this.Invoke("ObterIdCadastroOrcamento", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ObterIdCadastroOrcamentoAsync() {
            this.ObterIdCadastroOrcamentoAsync(null);
        }
        
        /// <remarks/>
        public void ObterIdCadastroOrcamentoAsync(object userState) {
            if ((this.ObterIdCadastroOrcamentoOperationCompleted == null)) {
                this.ObterIdCadastroOrcamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterIdCadastroOrcamentoOperationCompleted);
            }
            this.InvokeAsync("ObterIdCadastroOrcamento", new object[0], this.ObterIdCadastroOrcamentoOperationCompleted, userState);
        }
        
        private void OnObterIdCadastroOrcamentoOperationCompleted(object arg) {
            if ((this.ObterIdCadastroOrcamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterIdCadastroOrcamentoCompleted(this, new ObterIdCadastroOrcamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    public delegate void ObterDeputadosCompletedEventHandler(object sender, ObterDeputadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterDeputadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterDeputadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    public delegate void ObterPartidosCDCompletedEventHandler(object sender, ObterPartidosCDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterPartidosCDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterPartidosCDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    public delegate void ObterPartidosBlocoCDCompletedEventHandler(object sender, ObterPartidosBlocoCDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterPartidosBlocoCDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterPartidosBlocoCDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    public delegate void ObterDetalhesDeputadoCompletedEventHandler(object sender, ObterDetalhesDeputadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterDetalhesDeputadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterDetalhesDeputadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    public delegate void ObterLideresBancadasCompletedEventHandler(object sender, ObterLideresBancadasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterLideresBancadasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterLideresBancadasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    public delegate void ObterIdCadastroOrcamentoCompletedEventHandler(object sender, ObterIdCadastroOrcamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1085.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterIdCadastroOrcamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterIdCadastroOrcamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591