name: .NET Core

on:
  push:
    branches: [ master, deputados-estaduais ]
  pull_request:
    branches: [ master, deputados-estaduais ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    
    - name: Install .NET dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        dotnet restore ./OPS.API/OPS.API.csproj
        dotnet restore ./OPS.Importador/OPS.Importador.csproj
      
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
        cache-dependency-path: OPS.Site/package-lock.json
      
    - name: Cache Node Modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: node-modules-${{ hashFiles('**/package-lock.json') }}
          
    - name: Install Node.js dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: OPS.Site
      
    - name: Build .NET
      run: |
        dotnet build OPS.API --configuration Release --no-restore
        dotnet build OPS.Importador --configuration Release --no-restore
    
    - name: Publish Node.js
      run: npm run build --if-present
      working-directory: OPS.Site
      
    - name: Publish .NET
      run: |
        dotnet publish OPS.API --configuration Release -o ops-api
        rm -r ops-api/runtimes
        dotnet publish OPS.Importador --configuration Release -o ops-importador
        rm -r ops-importador/runtimes

    - uses: actions/upload-artifact@v3
      with:
        name: ops-api
        path: ops-api/**
        if-no-files-found: error

    - uses: actions/upload-artifact@v3
      with:
        name: ops-importador
        path: ops-importador/**
        if-no-files-found: error


  deploy:
    needs: build
    runs-on: [self-hosted, king-host]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ops-api
        path: ~/ops-api/

    - uses: actions/download-artifact@v3
      with:
        name: ops-importador
        path: ~/ops-importador/

    - name: Deploy dos arquivos na pasta final
      run: |
        /home/vanderlei/ops-importador-deploy.sh
        /home/vanderlei/ops-api-deploy.sh